apiVersion: v1
kind: Secret
metadata:
  name: rbac-generator-credentials
type: Opaque
stringData:
  APP_USERNAME: admin
  APP_PASSWORD_HASH: "REPLACE_WITH_OUTPUT_OF_make_hash-password_PASSWORD=yourpassword"
